services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                INSTALL_XDEBUG: ${INSTALL_XDEBUG} # Ativa Xdebug para dev
                APP_ENV: ${APP_ENV} # Define o ambiente (dev ou produção)
        container_name: revenda_mais_app
        volumes:
            - .:/var/www/html:delegated
        environment:
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - revenda_mais_network
        depends_on:
            - revenda_mais_mysql
            - revenda_mais_redis

    nginx:
        image: nginx:latest
        container_name: revenda_mais_nginx
        volumes:
            - .:/var/www/html:delegated
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - revenda_mais_network
        depends_on:
            - app

    revenda_mais_mysql:
        image: mysql:8.0
        container_name: revenda_mais_mysql
        environment:
            MYSQL_DATABASE: revenda_mais
            MYSQL_USER: revenda_mais_user
            MYSQL_PASSWORD: revenda_mais_password
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - revenda_mais_network
        ports:
            - "3306:3306"

    revenda_mais_redis:
        image: redis:7
        container_name: revenda_mais_redis
        networks:
            - revenda_mais_network
        ports:
            - "6379:6379"

networks:
    revenda_mais_network:
        driver: bridge

volumes:
    mysql_data:
